# Generated by Django 2.1.3 on 2018-12-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobina',
            fields=[
                ('bob_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('bob_numero', models.IntegerField(verbose_name='Número de Bobina')),
                ('bob_fecha', models.DateField(verbose_name='Fecha')),
                ('bob_hora', models.TimeField(verbose_name='Hora')),
                ('bob_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('bob_observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
            ],
            options={
                'db_table': 'bobina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BobinaMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bob_metro', models.FloatField(blank=True, null=True, verbose_name='Metros Totales')),
                ('bob_peso', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('bob_id', models.ForeignKey(blank=True, db_column='bob_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobinamedida_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name': 'Metro/Peso Bobinas',
                'verbose_name_plural': 'Metro/Peso Bobinas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BobinaRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bor_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('bor_hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('bor_estatus', models.CharField(choices=[('A', 'Asignada'), ('F', 'Finalizado')], default='I', max_length=1)),
                ('bob_id', models.ForeignKey(blank=True, db_column='bob_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobinaremision_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name': 'Bobina Remisión',
                'verbose_name_plural': 'Bobinas Remisiones',
                'db_table': 'bobinaremision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('caj_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('caj_nro', models.IntegerField(verbose_name='Número de Caja')),
                ('caj_peso', models.FloatField(verbose_name='Peso')),
            ],
            options={
                'db_table': 'caja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CajaBobina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbo_metros', models.FloatField(blank=True, null=True, verbose_name='Metros')),
                ('bob_id', models.ForeignKey(blank=True, db_column='bob_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajabobina_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
                ('caj_id', models.ForeignKey(blank=True, db_column='caj_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajabobina_caja', to='extrusoras_app.Caja', verbose_name='Caja')),
            ],
            options={
                'verbose_name': 'Bobina por Caja',
                'verbose_name_plural': 'Bobinas por Cajas',
                'db_table': 'cajabobina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('col_descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dep_descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('dep_bach_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='Código de Bachmaster')),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('maq_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('maq_encabezado', models.CharField(max_length=6, verbose_name='Encabezado')),
                ('maq_nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('maq_activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('dep_id', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='maquina_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name_plural': 'Máquinas',
                'db_table': 'maquina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Masivo',
            fields=[
                ('mas_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mas_descripcion', models.TextField(verbose_name='Contenido')),
                ('mas_file', models.FileField(upload_to='masivos/', verbose_name='Archivo')),
                ('mas_fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('mas_type', models.CharField(choices=[('R', 'Remisiones'), ('P', 'Productos')], default='P', max_length=1, verbose_name='Tipo archivo masivo')),
            ],
            options={
                'verbose_name': 'Archivo Masivo',
                'verbose_name_plural': 'Archivos masivos',
                'db_table': 'archivosmasivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mat_descripcion', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'mat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionBarnizado',
            fields=[
                ('meb_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('meb_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('meb_fecha', models.DateField(verbose_name='Fecha')),
                ('meb_hora', models.TimeField(verbose_name='Hora')),
                ('meb_metro', models.FloatField(verbose_name='Metros')),
                ('meb_ancho_plano', models.FloatField(verbose_name='Medición de Ancho Plano')),
                ('meb_dur_plas', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dureza de plasta')),
                ('meb_cata_barniz', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Catalización tinta barniz')),
                ('meb_vis_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 1')),
                ('meb_vis_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 2')),
                ('meb_temp_area', models.FloatField(blank=True, null=True, verbose_name='Temperatura área')),
                ('meb_hume_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Humedad del área')),
                ('meb_prue_cura', models.CharField(blank=True, max_length=1, null=True, verbose_name='Prueba de curado de tinta')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medbar_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Barnizado',
                'db_table': 'medicionbarnizado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionConversion',
            fields=[
                ('meo_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('meo_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('meo_fecha', models.DateField(verbose_name='Fecha')),
                ('meo_hora', models.TimeField(verbose_name='Hora')),
                ('meo_metro', models.FloatField(verbose_name='Metros')),
                ('meo_ancho_plano', models.FloatField(verbose_name='Medición de Ancho Plano')),
                ('meo_piezas', models.SmallIntegerField(blank=True, null=True, verbose_name='Piezas')),
                ('meo_largo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Medición de Largo')),
                ('meo_sell_izq', models.FloatField(blank=True, null=True, verbose_name='Fuerza sello lateral izquierdo')),
                ('meo_sell_med', models.FloatField(blank=True, null=True, verbose_name='Fuerza sello medio')),
                ('meo_sell_der', models.FloatField(blank=True, null=True, verbose_name='Fuerza sello lateral derecho')),
                ('meo_distancia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Distancia de sello a impresión')),
                ('meo_apariencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Apariencia')),
                ('meo_fuer_sello', models.FloatField(blank=True, null=True, verbose_name='Medición de Fuerza de sello')),
                ('meo_calibre', models.SmallIntegerField(blank=True, null=True, verbose_name='Medición de calibre')),
                ('meo_burbuja', models.CharField(blank=True, max_length=1, null=True, verbose_name='Prueba de burbuja')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medcon_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Conversión',
                'db_table': 'medicionconversion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionCorrugado',
            fields=[
                ('mec_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mec_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('mec_fecha', models.DateField(verbose_name='Fecha')),
                ('mec_hora', models.TimeField(verbose_name='Hora')),
                ('mec_metro', models.FloatField(verbose_name='Metros')),
                ('mec_ancho_plano', models.FloatField(verbose_name='Medición de Ancho Plano')),
                ('mec_apli_aceite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aplicación de Aceite')),
                ('mec_alt_stick', models.FloatField(blank=True, null=True, verbose_name='Altitud del stick')),
                ('mec_des_tinta', models.CharField(blank=True, max_length=1, null=True, verbose_name='Prueba de desprendimiento de tinta')),
                ('mec_apariencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Apariencia')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medcor_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Corrugado',
                'db_table': 'medicioncorrugado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionEmpaque',
            fields=[
                ('mem_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mem_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('mem_fecha', models.DateField(verbose_name='Fecha')),
                ('mem_hora', models.TimeField(verbose_name='Hora')),
                ('mem_metro', models.FloatField(verbose_name='Metros')),
                ('mem_kilo', models.FloatField(verbose_name='Kilos')),
                ('mem_apariencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Apariencia')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medemp_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Empaque',
                'db_table': 'medicionempaque',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionExtrusora',
            fields=[
                ('mee_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mee_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('mee_fecha', models.DateField(verbose_name='Fecha')),
                ('mee_hora', models.TimeField(verbose_name='Hora')),
                ('mee_metro', models.FloatField(verbose_name='Metros')),
                ('mee_ancho_plano', models.CharField(max_length=8, verbose_name='Ancho Plano')),
                ('mee_deslamine', models.CharField(max_length=1, null=True, verbose_name='Deslamine')),
                ('mee_encog_hor', models.PositiveSmallIntegerField(null=True, verbose_name='Encogimiento horizontal')),
                ('mee_encog_ver', models.PositiveSmallIntegerField(null=True, verbose_name='Encogimiento vertical')),
                ('mee_calibre_frontal', models.SmallIntegerField(null=True, verbose_name='Calibre Frontal')),
                ('mee_calibre_reverso', models.SmallIntegerField(null=True, verbose_name='Calibre Reverso')),
                ('mee_temperatura', models.FloatField(null=True, verbose_name='Temperatura de tunel')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medext_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Extrusión',
                'db_table': 'medicionextrusora',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionImpresion',
            fields=[
                ('mei_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mei_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('mei_fecha', models.DateField(verbose_name='Fecha')),
                ('mei_hora', models.TimeField(verbose_name='Hora')),
                ('mei_metro', models.FloatField(verbose_name='Metros')),
                ('mei_ancho_plano', models.FloatField(verbose_name='Medición de Ancho Plano')),
                ('mei_cat_blanca', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Catalización tinta blanca')),
                ('mei_cat_color', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Catalización tinta colores')),
                ('mei_vis_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 1')),
                ('mei_vis_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 2')),
                ('mei_vis_3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 3')),
                ('mei_vis_4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 4')),
                ('mei_vis_5', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 5')),
                ('mei_vis_6', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 6')),
                ('mei_vis_7', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 7')),
                ('mei_vis_8', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viscosidad Unidad 8')),
                ('mei_temp_infrarojo', models.FloatField(blank=True, null=True, verbose_name='Temperatura infrarojo')),
                ('mei_temp_tablero', models.FloatField(blank=True, null=True, verbose_name='Temperatura tablero')),
                ('mei_temp_area', models.FloatField(blank=True, null=True, verbose_name='Temperatura área')),
                ('mei_hume_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Humedad del área')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medimp_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Impresión',
                'db_table': 'medicionimpresion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionRectificado',
            fields=[
                ('mer_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mer_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('mer_fecha', models.DateField(verbose_name='Fecha')),
                ('mer_hora', models.TimeField(verbose_name='Hora')),
                ('mer_metro', models.FloatField(verbose_name='Metros')),
                ('mer_ancho_plano', models.FloatField(verbose_name='Medición de Ancho Plano')),
                ('mer_apariencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Apariencia')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medrec_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Rectificado',
                'db_table': 'medicionrectificado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicionRefilado',
            fields=[
                ('mef_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mef_numero', models.PositiveSmallIntegerField(verbose_name='Número de Medición')),
                ('mef_fecha', models.DateField(verbose_name='Fecha')),
                ('mef_hora', models.TimeField(verbose_name='Hora')),
                ('mef_metro', models.FloatField(verbose_name='Metros')),
                ('mef_ancho_plano', models.FloatField(verbose_name='Medición de Ancho Plano')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='medref_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
            ],
            options={
                'verbose_name_plural': 'Mediciones del Proceso Refilado',
                'db_table': 'medicionrefilado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Muestro',
            fields=[
                ('mue_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('mue_clave', models.CharField(max_length=10, verbose_name='Clave de Muestro')),
                ('mue_descripcion', models.CharField(max_length=100, verbose_name='Nombre')),
                ('mue_tipo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('mue_campo', models.CharField(max_length=100, verbose_name='Campo en la base de datos')),
                ('dep_id', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='muestro_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento')),
            ],
            options={
                'db_table': 'muestro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('ope_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('ope_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ope_type', models.CharField(choices=[('O', 'Operario'), ('S', 'Supervisor'), ('C', 'Calidad')], default='O', max_length=1, verbose_name='Tipo usuario')),
                ('dep_id', models.ManyToManyField(db_column='dep_id', related_name='operario_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('pro_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código')),
                ('pro_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('pro_medida', models.CharField(blank=True, max_length=15, null=True, verbose_name='Medida')),
                ('pro_kore', models.FloatField(blank=True, null=True, verbose_name='Kore')),
                ('pro_kgs', models.FloatField(blank=True, null=True, verbose_name='Peso Kgs')),
                ('col_id', models.ForeignKey(blank=True, db_column='col_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_color', to='extrusoras_app.Color', verbose_name='Color')),
                ('dep_id', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='producto_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento')),
                ('mat_id', models.ForeignKey(blank=True, db_column='mat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_mat', to='extrusoras_app.Mat', verbose_name='Mat')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('rem_id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Número de Remisión')),
                ('rem_nextid', models.CharField(blank=True, max_length=12, null=True, verbose_name='Remisión Siguiente')),
                ('rem_estatus', models.CharField(choices=[('E', 'En espera'), ('I', 'Iniciado'), ('F', 'Finalizado')], default='E', max_length=1)),
                ('pro_id', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, related_name='remision_producto', to='extrusoras_app.Producto', verbose_name='Producto')),
                ('pro_nextid', models.ForeignKey(blank=True, db_column='pro_nextid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remision_nextproducto', to='extrusoras_app.Producto', verbose_name='Producto Siguiente')),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
                'db_table': 'remision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RemisionTmp',
            fields=[
                ('rem_id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Número de Remisión')),
                ('pro_id', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, related_name='remisiontmp_producto', to='extrusoras_app.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Remisión Temporal',
                'verbose_name_plural': 'Remisiones Temporales',
                'db_table': 'remisiontmp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('rev_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('rev_fecha', models.DateField(verbose_name='Fecha')),
                ('rev_hora', models.TimeField(verbose_name='Hora')),
                ('bob_id', models.ForeignKey(db_column='bob_id', on_delete=django.db.models.deletion.CASCADE, related_name='revision_bobina', to='extrusoras_app.Bobina', verbose_name='Bobina')),
                ('dep_id', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='revision_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento')),
                ('ope_id', models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='revision_operario', to='extrusoras_app.Operario', verbose_name='Operario')),
            ],
            options={
                'db_table': 'revision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('uni_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('uni_descripcion', models.CharField(max_length=30, verbose_name='Descripción')),
                ('uni_conversion', models.FloatField(default=1, verbose_name='Conversión')),
                ('uni_abreviacion', models.CharField(blank=True, max_length=5, verbose_name='Abreviación')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidadmedida',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medicionrefilado',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='refilado_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicionrectificado',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='rectificado_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicionimpresion',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='impresion_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicionextrusora',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='extrusion_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicionempaque',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='empaque_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicioncorrugado',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='corrugado_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicionconversion',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='medicionbarnizado',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='barnizado_operario', to='extrusoras_app.Operario', verbose_name='Operario que tomó la medida'),
        ),
        migrations.AddField(
            model_name='caja',
            name='bobinas',
            field=models.ManyToManyField(through='extrusoras_app.CajaBobina', to='extrusoras_app.Bobina'),
        ),
        migrations.AddField(
            model_name='caja',
            name='dep_id',
            field=models.ForeignKey(blank=True, db_column='dep_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='caja',
            name='maq_id',
            field=models.ForeignKey(blank=True, db_column='maq_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_maquina', to='extrusoras_app.Maquina', verbose_name='Maquina'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ope_id',
            field=models.ForeignKey(db_column='ope_id', on_delete=django.db.models.deletion.CASCADE, related_name='caja_operario', to='extrusoras_app.Operario', verbose_name='Operario que introdujo la caja'),
        ),
        migrations.AddField(
            model_name='caja',
            name='rem_id',
            field=models.ForeignKey(blank=True, db_column='rem_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_remision', to='extrusoras_app.Remision', verbose_name='Remisión'),
        ),
        migrations.AddField(
            model_name='bobinaremision',
            name='maq_id',
            field=models.ForeignKey(blank=True, db_column='maq_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobinaremision_maquina', to='extrusoras_app.Maquina', verbose_name='Maquina'),
        ),
        migrations.AddField(
            model_name='bobinaremision',
            name='ope_id',
            field=models.ForeignKey(blank=True, db_column='ope_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobinaremision_operario', to='extrusoras_app.Operario', verbose_name='Operario que asignó la bobina'),
        ),
        migrations.AddField(
            model_name='bobinaremision',
            name='rem_id',
            field=models.ForeignKey(blank=True, db_column='rem_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobinaremision_remision', to='extrusoras_app.Remision', verbose_name='Remisión'),
        ),
        migrations.AddField(
            model_name='bobinamedida',
            name='dep_id',
            field=models.ForeignKey(blank=True, db_column='dep_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobinamedida_departamento', to='extrusoras_app.Departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='bobina',
            name='remisiones',
            field=models.ManyToManyField(through='extrusoras_app.BobinaRemision', to='extrusoras_app.Remision'),
        ),
    ]
